# SonarQube Cloud organization
sonar.organization=himanidhawan4

# SonarQube Cloud project
sonar.projectKey=himanidhawan4_release-portal-security-gate-test

# Project name
sonar.projectName=release-portal-security-gate-test

# Scan the entire project
sonar.sources=.

# Test files
sonar.tests=tests

# Exclude test files from main source analysis
sonar.exclusions=tests/**

# Encoding
sonar.sourceEncoding=UTF-8